services:
  backend:
    build: ./backend
    container_name: receipt-backend
    restart: always
    environment:
      - BACKEND_SECRET_KEY=una-chiave-molto-lunga-e-casuale
      - ADMIN_USERNAME=efurlan
      - ADMIN_PASSWORD=efurlan123!
    volumes:
      - /opt/data/receipt-app/backend_data:/app/data
    ports:
      - 8000:8000
    networks:
      - proxy-network
  frontend:
    build: ./frontend
    container_name: receipt-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3001:80
    networks:
      - proxy-network
networks:
  proxy-network:
    external: true




