services:
  backend:
    build: ./backend
    container_name: receipt-backend
    restart: always
    env_file:
      - /opt/env/.env
    volumes:
      - /opt/data/receipt-app/backend_data:/app/data
    ports:
      - 8000:8000
    networks:
      - proxy-network
  frontend:
    build: ./frontend
    container_name: receipt-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3001:80
    networks:
      - proxy-network
  ollama:
    image: ollama/ollama:latest
    container_name: receipt-ollama
    profiles:
      - ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_HOST=0.0.0.0
    devices:
      - /dev/dri:/dev/dri
    networks:
      - proxy-network

volumes:
  ollama_data:

networks:
  proxy-network:
    external: true




