name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Questo dice a GitHub di eseguire i comandi sul TUO Raspberry
    steps:
     - name: Update code Restart Container
        run: |
          cd /opt/stacks/receipt-app
          git pull origin main
          docker compose up -d --build
